# Generated by Django 5.0.3 on 2024-04-07 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webeducation', '0006_courseform_student_course_number_alter_student_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseForm',
        ),
    ]
