# Generated by Django 5.0.3 on 2024-04-07 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webeducation', '0007_delete_courseform'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseForm',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webeducation.course')),
            ],
            bases=('webeducation.course',),
        ),
    ]
