# Generated by Django 5.0.3 on 2024-04-07 12:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webeducation', '0008_courseform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_number',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webeducation.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.DeleteModel(
            name='CourseForm',
        ),
    ]
