# Generated by Django 5.0.3 on 2024-04-13 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webeducation', '0010_subjectrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='course_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webeducation.course'),
        ),
    ]
