# Generated by Django 5.0.3 on 2024-04-16 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webeducation', '0011_task_course_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='webeducation.subject'),
        ),
    ]
