# Generated by Django 5.0.3 on 2024-04-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webeducation', '0012_course_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
    ]
