# Generated by Django 5.0.3 on 2024-04-17 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webeducation', '0013_remove_course_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='task_submissions/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webeducation.student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webeducation.task')),
            ],
        ),
    ]
