# Generated by Django 5.0.3 on 2024-05-04 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webeducation', '0014_tasksubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_text', models.TextField()),
                ('solution_file', models.FileField(upload_to='task_solutions/%Y/%m/%d/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_solutions', to='webeducation.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_solutions', to='webeducation.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskSubmission',
        ),
    ]
