# Generated by Django 5.0.3 on 2024-05-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webeducation', '0016_alter_tasksolution_solution_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksolution',
            name='solution_file',
            field=models.FileField(blank=True, null=True, upload_to='task_solutions/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tasksolution',
            name='solution_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
