# Generated by Django 5.0.3 on 2024-05-13 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webeducation', '0018_alter_tasksolution_solution_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksolution',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_solutions', to='webeducation.task'),
        ),
        migrations.AlterField(
            model_name='tasksolution',
            name='solution_file',
            field=models.FileField(blank=True, null=True, upload_to='task_solutions/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tasksolution',
            name='solution_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
