# Generated by Django 5.0.3 on 2024-05-23 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webeducation', '0019_tasksolution_task_alter_tasksolution_solution_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksolution',
            name='solution_text',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='tasksolution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_solutions', to='webeducation.task'),
        ),
    ]
