# Generated by Django 5.0.3 on 2024-05-24 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webeducation', '0020_alter_tasksolution_solution_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjectPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=None)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webeducation.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webeducation.subject')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webeducation.task')),
            ],
        ),
    ]
