# Generated by Django 5.0.3 on 2024-05-24 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webeducation', '0021_studentsubjectpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubjectpoints',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='studentsubjectpoints',
            name='points',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
