# Generated by Django 5.0.3 on 2024-05-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webeducation', '0023_quiz_quizquestion_quizoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], null=True),
        ),
    ]
