# Generated by Django 5.0.3 on 2024-05-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webeducation', '0024_quiz_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizoption',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizoption',
            name='option_text',
            field=models.CharField(max_length=5),
        ),
    ]
