# Generated by Django 5.0.3 on 2024-05-30 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webeducation', '0025_quizoption_text_alter_quiz_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webeducation.quizoption')),
                ('quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webeducation.quizquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webeducation.student')),
            ],
        ),
    ]
