# Generated by Django 5.0.3 on 2024-06-05 21:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webeducation', '0026_quizanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='chosen_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webeducation.quizoption'),
        ),
    ]
