# Generated by Django 5.0.3 on 2024-06-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webeducation', '0027_alter_quiz_time_limit_alter_quizanswer_chosen_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=7),
        ),
    ]
